In [ ]:
import numpy as np

In [ ]:
arr = [1,2,3,4,5]
np_arr = np.array(arr)
print(type(arr))
print(type(np_arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
arr = np.arange(25).reshape(5,5)

Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\ms-python.python-2024.22.0-win32-x64\python_files\python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
ValueError: cannot reshape array of size 1 into shape (5,5)



In [ ]:
print(arr[1][2])

7


In [ ]:
print(arr[1:3, :2]) #슬라이싱

[[ 5  6]
 [10 11]]


In [ ]:
#원본 배열을 수정하지 않으려면 np.copy를 사용한다.

In [ ]:
arr2 = arr
arr[0][0] = 15
print(arr)
print(arr2) #원본은 변경도 안했는데 바뀌어버린다.

[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
arr = np.arange(15).reshape(3,5)
arr2 = arr.copy()
arr2[0][0] =15
print(arr)
print(arr2)